# texto = "Isso é um teste.".split()
# texto = "   Olá,    mundo!   ".split()
# texto = "Palavra Palavra palavra".split()
# texto = "Este é um teste de contagem de palavras.".split()
# texto = "".split()
# texto = "Maria tem 10 anos.".split()
# texto = "Olá ,  Mundo".split()
# texto = "Em uma tarde ensolarada, 3 crianças brincavam no parque. De repente, encontraram um mapa misterioso, com anotações enigmáticas: 'Vire à esquerda, depois à direita, e avance 100 passos!' Eles, empolgados, seguiram as instruções cuidadosamente, contando cada passo com atenção. No caminho , encontraram diversos obstáculos: pedras, galhos e até um riacho raso. O mapa os levou a uma árvore antiga, com raízes grossas e folhas densas. 'Aqui deve ser!', exclamou João, o mais velho. Mas,   sob a árvore, só encontraram uma caixa vazia e um bilhete: 'A verdadeira aventura está na jornada, não no destino. Parabéns por chegarem até aqui!' Desapontados, mas ainda animados, decidiram continuar explorando. 'Vamos ver o que mais podemos descobrir!', disse Maria, a mais aventureira do grupo. E assim, a busca por tesouros se transformou em uma tarde de descobertas e diversão. No final, o que realmente importava era a amizade e as memórias que criaram juntos.".split()
# texto = "Oi".split()

texto = input('Digite um texto: ').split()
print(f'O texto contem {len(texto)} palavra(s)')